version: '3.8'

services:
  web:
    image: kateivan/django_project
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8080:8000
    env_file: 
      - ./.env.prod
    depends_on:
      - db  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
      
volumes:
  postgres_volume:   
